version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Веб-додаток буде доступний на порту 8080
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root       # Кореневий пароль
      MYSQL_DATABASE: moja_strona     # Ім'я бази даних
      MYSQL_USER: user                # Користувач
      MYSQL_PASSWORD: password        # Пароль користувача
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80" # PhpMyAdmin буде доступний на порту 8081
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password

volumes:
  db_data:
